// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: did.proto

package did_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DidClient is the client API for Did service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DidClient interface {
	PushLog(ctx context.Context, in *Log, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type didClient struct {
	cc grpc.ClientConnInterface
}

func NewDidClient(cc grpc.ClientConnInterface) DidClient {
	return &didClient{cc}
}

func (c *didClient) PushLog(ctx context.Context, in *Log, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/Did/PushLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DidServer is the server API for Did service.
// All implementations must embed UnimplementedDidServer
// for forward compatibility
type DidServer interface {
	PushLog(context.Context, *Log) (*ResponseStatus, error)
	mustEmbedUnimplementedDidServer()
}

// UnimplementedDidServer must be embedded to have forward compatible implementations.
type UnimplementedDidServer struct {
}

func (UnimplementedDidServer) PushLog(context.Context, *Log) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushLog not implemented")
}
func (UnimplementedDidServer) mustEmbedUnimplementedDidServer() {}

// UnsafeDidServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DidServer will
// result in compilation errors.
type UnsafeDidServer interface {
	mustEmbedUnimplementedDidServer()
}

func RegisterDidServer(s grpc.ServiceRegistrar, srv DidServer) {
	s.RegisterService(&Did_ServiceDesc, srv)
}

func _Did_PushLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DidServer).PushLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Did/PushLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DidServer).PushLog(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

// Did_ServiceDesc is the grpc.ServiceDesc for Did service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Did_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Did",
	HandlerType: (*DidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushLog",
			Handler:    _Did_PushLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "did.proto",
}
